services:
  db:
    image: postgres
    restart: always
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command:
      bash -c " cd django_stock_app && python manage.py migrate && 
      python manage.py create_admin &&
      python manage.py populate_db && 
      python manage.py runserver 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db