# Generated by Django 4.1.4 on 2022-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcompanies',
            name='company_abbreviation',
            field=models.CharField(help_text='Company Abbreviation', max_length=10, unique=True),
        ),
    ]
