# Generated by Django 4.1.4 on 2023-01-03 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_id', models.CharField(help_text='Portfolio primary key user_portfolio_name', max_length=150, unique=True)),
                ('name', models.CharField(help_text='User portfolio name', max_length=20, unique=True)),
                ('create_date', models.DateField(auto_now_add=True, help_text='Date of portfolio creation')),
                ('balance', models.FloatField(default=10000, help_text='Start balance 10k PLN')),
                ('user', models.ForeignKey(help_text='Portfolio owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='Company Abbreviation', max_length=10, unique=True)),
                ('stock_buy_date', models.DateField(auto_now=True, help_text='Date of adding the stock')),
                ('amount', models.IntegerField(help_text='Number of stocks in portfolio')),
                ('stock_price', models.FloatField(help_text='Average stock price')),
                ('portfolio_id', models.ForeignKey(help_text='Portfolio FK', on_delete=django.db.models.deletion.DO_NOTHING, to='portfolios.portfolio', to_field='portfolio_id')),
            ],
        ),
    ]
