# Generated by Django 4.1.4 on 2023-01-07 16:25

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliostocks",
            name="amount",
            field=models.IntegerField(
                help_text="Number of stocks in portfolio",
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
